#!/usr/bin/env bash
set -euo pipefail

MANIFEST=""
OUT_PATH=""

usage() {
  cat <<'USAGE'
Usage: scripts/release/write-gcp-image-tfvars.sh --image-manifest <cloud-image-build-manifest.json> --out <path>

Writes a Terraform tfvars fragment containing digest-addressed control-plane
image inputs for bucephalus-cloud/infra/gcp. The source image manifest must be
pushed and verified; local image-build manifests are inspection evidence only.
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --image-manifest)
      MANIFEST="${2:-}"
      shift 2
      ;;
    --out)
      OUT_PATH="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "${MANIFEST}" || -z "${OUT_PATH}" ]]; then
  usage >&2
  exit 2
fi

if [[ ! -f "${MANIFEST}" ]]; then
  echo "image manifest does not exist: ${MANIFEST}" >&2
  exit 2
fi

if ! command -v bun >/dev/null 2>&1; then
  echo "required command not found: bun" >&2
  exit 2
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
"${ROOT_DIR}/scripts/release/verify-cloud-image-build-manifest.sh" "${MANIFEST}"

mkdir -p "$(dirname "${OUT_PATH}")"
WORK_DIR="$(mktemp -d)"
cleanup() {
  rm -rf "${WORK_DIR}"
}
trap cleanup EXIT
WRITE_JS="${WORK_DIR}/write-gcp-image-tfvars.mjs"
cat > "${WRITE_JS}" <<'JS'
const manifest = JSON.parse(await Bun.file(process.env.MANIFEST).text());
if (manifest.pushed !== true) {
  console.error("image manifest must be pushed=true to produce deploy tfvars");
  process.exit(1);
}

const byComponent = new Map(manifest.images.map((image) => [image.component, image]));
const required = {
  api_image_digest: "api",
  pool_controller_image_digest: "pool-controller",
  migration_image_digest: "migrations",
};
const garComponentRepo = /^([a-z0-9-]+-docker\.pkg\.dev\/[a-z0-9][a-z0-9-]*\/[a-z0-9][a-z0-9._-]*\/[a-z0-9][a-z0-9._-]*)\/(api|pool-controller|migrations|worker)$/;

function fail(message) {
  console.error(message);
  process.exit(1);
}

let deployRepositoryFamily = null;
for (const component of Object.values(required)) {
  const image = byComponent.get(component);
  const match = image?.image_repository?.match(garComponentRepo);
  if (!match || match[2] !== component) {
    fail(`${component}.image_repository must be a GCP Artifact Registry component repository`);
  }
  if (deployRepositoryFamily === null) {
    deployRepositoryFamily = match[1];
  } else if (match[1] !== deployRepositoryFamily) {
    fail("deploy tfvars image repositories must share one GCP Artifact Registry family");
  }
}

const lines = [
  "# Generated by scripts/release/write-gcp-image-tfvars.sh",
  "# Source: verified bucephalus_cloud_image_build_manifest_v1",
  `# Release version: ${manifest.release.version}`,
  `# Release git SHA: ${manifest.release.git_sha}`,
  `# Release manifest SHA256: ${manifest.release.manifest_sha256}`,
  "",
];

for (const [variable, component] of Object.entries(required)) {
  const image = byComponent.get(component);
  if (!image?.immutable_ref) {
    fail(`missing immutable image ref for ${component}`);
  }
  if (!image.immutable_ref.startsWith(`${image.image_repository}@`)) {
    fail(`${variable} must use the ${component} image_repository`);
  }
  lines.push(`${variable} = ${JSON.stringify(image.immutable_ref)}`);
}

lines.push("");
await Bun.write(process.env.OUT_PATH, lines.join("\n"));
console.log(`tfvars=${process.env.OUT_PATH}`);
JS
MANIFEST="${MANIFEST}" OUT_PATH="${OUT_PATH}" bun "${WRITE_JS}"
"${ROOT_DIR}/scripts/release/verify-gcp-image-tfvars.sh" \
  --image-manifest "${MANIFEST}" \
  --tfvars "${OUT_PATH}"
