#!/usr/bin/env python3
"""Workspace tool: read feed, search records, calculate exposure, submit scan.

Auto-generated by the synth-data preset library. Domain-agnostic.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

try:
    import yaml  # type: ignore
except ImportError:
    yaml = None


ROOT = Path(__file__).resolve().parents[1]
RECORDS = ROOT / "records"
EVENTS = ROOT / "events"
OUTPUT = ROOT / "output"


def _load(path: Path):
    text = path.read_text(encoding="utf-8")
    if path.suffix in (".yaml", ".yml"):
        if yaml is None:
            raise SystemExit("PyYAML not available in workspace runtime")
        return yaml.safe_load(text)
    if path.suffix == ".json":
        return json.loads(text)
    return text


def _all_records():
    out = {}
    if RECORDS.exists():
        for p in sorted(RECORDS.glob("**/*")):
            if p.is_file():
                rel = str(p.relative_to(ROOT))
                try:
                    out[rel] = _load(p)
                except Exception as exc:
                    out[rel] = {"_load_error": str(exc)}
    return out


def _excerpt(text: str, query: str, window: int = 80) -> str:
    lower = text.lower()
    q = query.lower()
    idx = lower.find(q)
    if idx < 0:
        return text[:window]
    start = max(0, idx - window // 2)
    end = min(len(text), idx + len(q) + window // 2)
    return text[start:end]


def _flatten(value, parent: str = ""):
    if isinstance(value, dict):
        for k, v in value.items():
            yield from _flatten(v, f"{parent}.{k}" if parent else str(k))
    elif isinstance(value, list):
        for i, v in enumerate(value):
            yield from _flatten(v, f"{parent}[{i}]")
    else:
        yield parent, value


def cmd_read_feed(_args) -> int:
    feed = EVENTS / "headline-pack.md"
    if not feed.exists():
        print(f"no event feed at {feed.relative_to(ROOT)}", file=sys.stderr)
        return 1
    sys.stdout.write(feed.read_text(encoding="utf-8"))
    return 0


def cmd_search_records(args) -> int:
    query = args.query
    hits = []
    for rel in sorted(p for p in (RECORDS, EVENTS) if p.exists() for _ in [0]):
        pass
    for root in (RECORDS, EVENTS):
        if not root.exists():
            continue
        for path in sorted(root.glob("**/*")):
            if not path.is_file():
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            if query.lower() in text.lower():
                hits.append(
                    {
                        "path": str(path.relative_to(ROOT)),
                        "excerpt": _excerpt(text, query),
                    }
                )
    print(json.dumps({"query": query, "hits": hits}, indent=2, sort_keys=True))
    return 0


def cmd_read_record(args) -> int:
    path = (ROOT / args.path).resolve()
    if ROOT not in path.parents and path != ROOT:
        raise SystemExit("record path escapes workspace")
    if not path.exists():
        raise SystemExit(f"no such file: {args.path}")
    sys.stdout.write(path.read_text(encoding="utf-8"))
    return 0


def cmd_calculate_exposure(args) -> int:
    """For each --entity-id, find downstream products → orders → revenue.

    The entity id may be an input id, component id, material id, or product id.
    The function walks: input/material → BOM components that list it
    → product_id → orders for that product. Inventory is summed per product.
    """
    targets = set(args.entity_id)
    records = _all_records()

    boms = records.get("records/bom.yaml", {}).get("boms", []) if isinstance(records.get("records/bom.yaml"), dict) else []
    orders = records.get("records/orders.yaml", {}).get("orders", []) if isinstance(records.get("records/orders.yaml"), dict) else []
    inventory = records.get("records/inventory.yaml", {}).get("inventory", []) if isinstance(records.get("records/inventory.yaml"), dict) else []

    affected_products: set[str] = set()
    # entity might be a product id directly
    for o in orders:
        if o.get("product_id") in targets:
            affected_products.add(o["product_id"])

    # or it walks through BOM
    for bom in boms:
        pid = bom.get("product_id")
        for comp in bom.get("components", []) or []:
            if comp.get("component_id") in targets:
                affected_products.add(pid)
            for inp in comp.get("inputs", []) or []:
                if inp in targets:
                    affected_products.add(pid)

    affected_orders = [o for o in orders if o.get("product_id") in affected_products]
    affected_customers = sorted({o["customer"] for o in affected_orders if o.get("customer")})
    revenue_at_risk = sum(int(o.get("quantity", 0)) * int(o.get("unit_revenue", 0)) for o in affected_orders)
    inv_for_affected = [i for i in inventory if i.get("product_id") in affected_products]
    inv_total = sum(int(i.get("quantity_available", 0)) for i in inv_for_affected)
    needed = sum(int(o.get("quantity", 0)) for o in affected_orders)

    result = {
        "queried_entity_ids": sorted(targets),
        "affected_products": sorted(affected_products),
        "affected_orders": [o.get("id") for o in affected_orders if o.get("id")],
        "affected_customers": affected_customers,
        "revenue_at_risk": revenue_at_risk,
        "constrained_inventory": inv_total < needed,
        "inventory_on_hand": inv_total,
        "inventory_needed": needed,
    }
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


def cmd_submit_scan(args) -> int:
    src = Path(args.path)
    if not src.is_absolute():
        src = ROOT / src
    if not src.exists():
        raise SystemExit(f"no such file: {args.path}")
    OUTPUT.mkdir(parents=True, exist_ok=True)
    dest = OUTPUT / src.name
    shutil.copy(src, dest)
    print(json.dumps({"submitted": str(dest.relative_to(ROOT))}, sort_keys=True))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Peter Gregory workspace tools")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("read_feed", help="Print the external event feed.")

    sr = sub.add_parser("search_records", help="Substring search across records/ and events/.")
    sr.add_argument("query")

    rr = sub.add_parser("read_record", help="Print one workspace-relative file.")
    rr.add_argument("path")

    ce = sub.add_parser("calculate_exposure", help="Compute downstream exposure for one or more entity ids.")
    ce.add_argument("--entity-id", action="append", required=True)

    ss = sub.add_parser("submit_scan", help="Copy the final scan to output/.")
    ss.add_argument("path")

    args = parser.parse_args()
    handler = {
        "read_feed": cmd_read_feed,
        "search_records": cmd_search_records,
        "read_record": cmd_read_record,
        "calculate_exposure": cmd_calculate_exposure,
        "submit_scan": cmd_submit_scan,
    }[args.command]
    return handler(args)


if __name__ == "__main__":
    raise SystemExit(main())
