[package]
name = "lab-analysis"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "lab_analysis"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
hex.workspace = true
include_dir.workspace = true
lab-core.workspace = true
rusqlite.workspace = true
serde_json.workspace = true
